name: Notify Telegram on Update

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Check for Python file updates and new modules
        id: check_updates
        run: |
          # Check for updated Python files
          git diff --name-only HEAD^ HEAD | grep '\.py$' > updated_files.txt || echo "No updates"
          
          # Check for newly added Python files
          git diff --name-only --diff-filter=A HEAD^ HEAD | grep '\.py$' > new_modules.txt || echo "No new modules"
          
          # Set outputs for updated and new modules
          echo "::set-output name=updated::$(cat updated_files.txt)"
          echo "::set-output name=new::$(cat new_modules.txt)"

      - name: Send Telegram Notification for Updates
        if: steps.check_updates.outputs.updated != ''
        run: |
          TOKEN="7555856648:AAFF_zq7THb2Dx1bxmdbsDMxkvWrlwAI74M"
          CHAT_ID="-1002297752617"
          MODULE_NAME=$(echo "${{ steps.check_updates.outputs.updated }}" | head -n 1 | sed 's/.*\///; s/\.py$//')
          MESSAGE="🚀 $MODULE_NAME has been updated by Owner!🚀"
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID&text=$MESSAGE&parse_mode=HTML"

      - name: Send Telegram Notification for New Modules
        if: steps.check_updates.outputs.new != ''
        run: |
          TOKEN="7555856648:AAFF_zq7THb2Dx1bxmdbsDMxkvWrlwAI74M"
          CHAT_ID="-1002297752617"
          NEW_MODULE_NAME=$(echo "${{ steps.check_updates.outputs.new }}" | head -n 1 | sed 's/.*\///; s/\.py$//')
          MESSAGE="🔰 $NEW_MODULE_NAME has been posted by Owner!🚀"
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID&text=$MESSAGE&parse_mode=HTML"
